### ISSUE TITLE
Domain name

### ISSUE THREAD

**Issue by sstur** [kiltjs/nitro#7]
Hey, let me know if you're interested in the domain name nitrojs.com. I'm happy to give it to you if you want it. I've had it for some time and not using it and not planning to renew it. So it's yours if you want it.

**Comment by jgermade** [comment]
Hi @sstur, really sorry for the delay in replying. Last months has being frenetic 😓 

Thanks a lot for offering the domain. Is perfect for this project!

**Comment by sstur** [comment]
Shoot, I already let it expire. I'll check if it's still in grace period..

**Comment by sstur** [comment]
It [expired on 12th March](https://who.is/whois/nitrojs.com). So the grace period is already over and it's in "redemption status" which I think is [kinda pricey to recover from](https://www.namecheap.com/support/knowledgebase/article.aspx/242/2207/what-is-domain-redemption-status).

If you want to recover it, let me know, if not maybe just try and grab it when it goes back on the market in a couple weeks.

**Comment by jgermade** [comment]
ook! thanks a lot @sstur !!

It would be great to renew domain before grace period ends. My email is: jesus@germade.es

**Comment by sstur** [comment]
Sorry to say that it looks like a squatter already grabbed the domain. Closing this issue.
